[tool.poetry]
name = "tutorial"
version = "0.2.0"
description = ""
authors = ["Peter Urban <peter.urban@ugent.be>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10, <3.13"
themachinethatgoesping = "0.25.0"
# jupyterlab = "^4.2.5"
# ipympl = "^0.9.4"
# nbmake = "^1.5.4"
# ipyleaflet = "^0.19.2"
# matplotlib = "3.9.0"
matplotlib = "3.9.0"
jupyterlab = "^4.2.5"
ipympl = "^0.9.4"
nbmake = "^1.5.4"
ipyleaflet = "^0.19.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
