#src: https://discourse.jupyter.org/t/how-to-reduce-mybinder-org-repository-startup-time/4956/2


name: Build Notebook Container
on: [push] # You may want to trigger this Action on other things than a push.
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        
    - name: checkout main repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        lfs: true

    - name: "install project"
      run: pip install -r test_requirements.txt

    - name: "run tests"
      run: pytest --nbmake **/*ipynb

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@master

    - name: update jupyter dependencies with repo2docker
      uses: machine-learning-apps/repo2docker-action@master
      with:
        DOCKER_USERNAME: themachinethatgoesping
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        MYBINDERORG_TAG: ${{ github.event.ref }}
        PUBLIC_REGISTRY_CHECK: true
        NO_PUSH: true
